[package]
name = "kurozumi-gui"
version.workspace = true
edition.workspace = true

[dependencies]
kurozumi-core = { workspace = true }
kurozumi-detect = { workspace = true }
kurozumi-parse = { workspace = true }

iced = { version = "0.14", features = ["tokio", "tiny-skia", "advanced"] }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
