base_url = "https://ryuuji.dev"
title = "Ryuuji"
description = "Desktop anime tracker that works while you watch"
compile_sass = true
minify_html = true
generate_feeds = false
build_search_index = false

[markdown]

[extra]
show_screenshots = false
github_url = "https://github.com/your-username/ryuuji"
