base_url = "https://ryuuji.dev"
title = "Ryuuji"
description = "Desktop app that automatically detects what you're watching and syncs your anime list"
compile_sass = true
minify_html = true
generate_feeds = false
build_search_index = false

[markdown]

[extra]
show_screenshots = true
github_url = "https://github.com/your-username/ryuuji"
